name: Shipping Dashboard CI/CD Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build: 
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Clone repo & checkout code
      uses: actions/checkout@v2 

    - name: Install Node.js
      uses: actions/setup-node@v2.4.0
      with:
        node-version: 14.x

    - name: Install NPM packages
      run: npm ci
      
    - name: Build project
      run: npm run build 

    - name: Run tests
      run: npm run test:unit

    - name: Upload production-ready build files
      uses: actions/upload-artifact@v2 
      with:
        name: production
        path: public

  deploy:
    name: Deploy
    needs: build 

    runs-on: ubuntu-latest

    steps:
    - name: Download artifact
      uses: actions/download-artifact@v2 

      with:
        name: production
        path: public

    - name: Deploy to Github pages
      uses: crazy-max/ghaction-github-pages@v2

      with:
        target_branch: gh-pages
        build_dir: public
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
